service: risecustomlogiclogic

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs14.x

    environment:
        APP_NAME: accounting
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
              - 'events:PutEvents'
          Resource:
              - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default

functions:
    makePayment:
        handler: src/makePayment.main
        events:
            - eventBridge:
                  pattern:
                      source:
                          - custom.risecustomlogicapi
                      detail-type:
                          - startProcess
